apiVersion: apps/v1
kind: Deployment
metadata:
  name: d1-gaming-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d1-gaming-frontend
  template:
    metadata:
      labels:
        app: d1-gaming-frontend
        version: 1.0.8
    spec:
      volumes: 
        - name: google-cloud-key
          secret: 
            secretName: compute-admin-key
      containers:
        - name: d1-gaming-frontend-container
          image: gcr.io/d1gamingapp/d1-gaming-frontend:v1.0.8
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/compute-admin-key.json
          resources:
            limits:
              cpu: 0.2
              memory: 1Gi
            requests:
              cpu: 0.2
              memory: 1Gi
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
              httpGet:
                path: /login
                port: 80
              periodSeconds: 30
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 5
                    
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "d1-gaming-frontend"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: "d1-gaming-frontend"
  type: "LoadBalancer"